FROM python:3

ENV TZ=Europe/Berlin
WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src .

VOLUME [ "/source" ]
VOLUME [ "/destination" ]

CMD [ "python", "./watchit.py" ]