version: '3'

services:
  renamer:
    image: tatort.renamer:0.9
    build: .
    volumes:
      - /Users/haiko/Documents/Temp/Docker/tatort:/source
      - /Users/haiko/Documents/Temp/tatort:/destination
